stages:
  - build-and-test

build-and-test:
  stage: build-and-test
  image: openjdk:21-oracle
  script:
    - chmod +x ./gradlew
    - ./gradlew build //jacocoTestReport
  artifacts:
    when: always
    paths:
      - build/reports/
  only:
    - main
